# This YAML file contains configmap objects,
# which are necessary to run csi opensds plugin.

kind: ConfigMap
apiVersion: v1
metadata:
  name: csi-configmap-opensdsplugin
data:
  opensdsendpoint: http://10.239.48.173:50040
  opensdsauthstrategy: noauth
  osauthurl: http://10.239.48.173/identity
  osusername: admin
  ospassword: opensds@123
  ostenantname: admin
  osprojectname: admin
  osuserdomainid: default
  passwordencrypter: aes
  enableEncrypted: F
  osuserdomainid: default

